version: '3.9'

services:
  server:
    build: .
    ports:
      - '1234:8000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '197515'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: